@baseUrl = http://localhost:3333
@contentType = application/json

# @name create_reservation
POST {{baseUrl}}/reservations
Content-Type: {{contentType}}

{
    "name": "John Doe",
    "phone": "85999999999"
}

###

# @name list_reservation
GET {{baseUrl}}/reservations
Content-Type: {{contentType}}

###


