version: '3.8'
# Para produção vamos utilizar bitnami/postgresql:11.11.0

services:
  postgres:
    container_name: nest-postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-services
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
